# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DollRoom',
            fields=[
                ('imageUrl', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=30)),
                ('peopleCount', models.IntegerField()),
                ('live_rtmp_url', models.CharField(default='', max_length=255)),
                ('user_rtmp_url', models.CharField(default='', max_length=255)),
                ('chatroom_id', models.IntegerField(default=0)),
                ('room_id', models.AutoField(default=10000, primary_key=True, serialize=False)),
            ],
        ),
    ]
