# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dollroom',
            name='room_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
