# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20170921_0637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(upload_to='goods_icon')),
                ('name', models.CharField(max_length=64)),
                ('price', models.FloatField()),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
    ]
