# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_commodity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='name',
            field=models.CharField(max_length=65),
        ),
    ]
