# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wechat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appid', models.CharField(default='', max_length=20, verbose_name='\u516c\u4f17\u53f7 ID')),
                ('alias', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u516c\u4f17\u53f7\u540d\u79f0')),
                ('service_type', models.IntegerField(choices=[(0, '\u8ba2\u9605\u53f7'), (1, '\u5347\u7ea7\u540e\u7684\u8ba2\u9605\u53f7'), (2, '\u670d\u52a1\u53f7')], default=0, verbose_name='\u516c\u4f17\u53f7\u7c7b\u578b')),
                ('nick_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u6635\u79f0')),
                ('head_img', models.URLField(blank=True, max_length=256, null=True, verbose_name='\u5934\u50cf')),
                ('user_name', models.CharField(max_length=32, verbose_name='\u5185\u90e8\u540d\u79f0')),
                ('qrcode_url', models.URLField(blank=True, max_length=256, null=True, verbose_name='\u4e8c\u7ef4\u7801URL')),
                ('authorized', models.BooleanField(verbose_name='\u6388\u6743')),
                ('verify_type', models.PositiveIntegerField(choices=[(-1, '\u672a\u8ba4\u8bc1'), (0, '\u5fae\u4fe1\u8ba4\u8bc1'), (1, '\u65b0\u6d6a\u5fae\u535a\u8ba4\u8bc1'), (2, '\u817e\u8baf\u5fae\u535a\u8ba4\u8bc1'), (3, '\u5df2\u8d44\u8d28\u8ba4\u8bc1\u901a\u8fc7\u4f46\u8fd8\u672a\u901a\u8fc7\u540d\u79f0\u8ba4\u8bc1'), (4, '\u5df2\u8d44\u8d28\u8ba4\u8bc1\u901a\u8fc7\u3001\u8fd8\u672a\u901a\u8fc7\u540d\u79f0\u8ba4\u8bc1\uff0c\u4f46\u901a\u8fc7\u4e86\u65b0\u6d6a\u5fae\u535a\u8ba4\u8bc1'), (5, '\u5df2\u8d44\u8d28\u8ba4\u8bc1\u901a\u8fc7\u3001\u8fd8\u672a\u901a\u8fc7\u540d\u79f0\u8ba4\u8bc1\uff0c\u4f46\u901a\u8fc7\u4e86\u817e\u8baf\u5fae\u535a\u8ba4\u8bc1')], verbose_name='\u8ba4\u8bc1\u7c7b\u578b')),
                ('funcscope_categories', models.CommaSeparatedIntegerField(max_length=64, verbose_name='\u6743\u9650\u96c6')),
                ('join_time', models.DateTimeField(auto_now_add=True, verbose_name='\u6388\u6743\u65f6\u95f4')),
            ],
            options={
                'get_latest_by': 'join_time',
                'verbose_name': '\u516c\u4f17\u53f7',
                'verbose_name_plural': '\u516c\u4f17\u53f7',
            },
        ),
    ]
